### ISSUE TITLE
Cannot invoke "org.apache.xerces.xni.XMLLocator.getExpandedSystemId()" because "this.locator" is null

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx#1029]
I occasionally see this error in my logs though it doesn't seem to have any negative effect, and it can be difficult to reproduce. I'm using https://git.eclipse.org/c/orbit/orbit-recipes.git/tree/apache/ant/org.apache.ant_1.10.10/src/eclipse/ip_log.xml and generated a DTD being referenced using xml-model, using the code action provided by LemMinX.

```
[Error - 10:42:07 AM] May 12, 2021 10:42:07 org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator doDiagnostics()
Message: Unexpected XMLValidator error
java.lang.NullPointerException: Cannot invoke "org.apache.xerces.xni.XMLLocator.getExpandedSystemId()" because "this.locator" is null
	at org.eclipse.lemminx.extensions.xerces.ExternalXMLDTDValidator.tryToBindWithExternalDTD(ExternalXMLDTDValidator.java:96)
	at org.eclipse.lemminx.extensions.xerces.ExternalXMLDTDValidator.emptyElement(ExternalXMLDTDValidator.java:144)
	at org.eclipse.lemminx.extensions.xerces.xmlmodel.XMLModelHandler.emptyElement(XMLModelHandler.java:204)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.parseXML(XMLValidator.java:293)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:123)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:50)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:64)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:46)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:162)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:171)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:521)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$26(XMLTextDocumentService.java:514)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by rgrunber** [comment]
I can actually reproduce this consistently by reformatting the document mentioned above, once the DTD is generated for it.

**Comment by rgrunber** [comment]
I've also seen very similar stacktrace :

```
[Error - 12:09:39 PM] May 25, 2021 12:09:38 org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator doDiagnostics()
Message: Unexpected XMLValidator error
java.lang.NullPointerException
	at org.eclipse.lemminx.extensions.xerces.ExternalXMLDTDValidator.tryToBindWithExternalDTD(ExternalXMLDTDValidator.java:96)
	at org.eclipse.lemminx.extensions.xerces.ExternalXMLDTDValidator.emptyElement(ExternalXMLDTDValidator.java:144)
	at org.eclipse.lemminx.extensions.xerces.xmlmodel.XMLModelHandler.emptyElement(XMLModelHandler.java:204)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.parseXML(XMLValidator.java:293)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:123)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:50)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:64)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:46)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:162)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:171)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:521)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$26(XMLTextDocumentService.java:514)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by angelozerr** [comment]
I cannot reproduce it, could youshare please your xml and dtd.

**Comment by rgrunber** [comment]
I'm no longer able to reproduce this either. Initially It seemed very easy to do so by simply having a simple xml document and generating a schema for it. Now it doesn't happen.

Feel free to also mark this as "not reproducible" (I can only close it). If it happens in the future, the stack trace is unique enough to be discovered in a search.
