### ISSUE TITLE
NPE in XSDValidator doDiagnostics with xs:import/@schemaLocation

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1073]
Given this XSD which defines bad.xsd:

```
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
	<xs:import
			namespace='http://foo'
			schemaLocation='http://foo bad.xsd' />
	<xs:element name='foo' />
</xs:schema> 
```

On windows OS I have an NPE:

```
[Error - 19:19:44] Jun 28, 2021 07:19:44 org.eclipse.lemminx.extensions.xsd.participants.diagnostics.XSDValidator doDiagnostics()
Message: Unexpected XSDValidator error
java.lang.NullPointerException
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:221)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:229)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:223)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResource(CacheResourcesManager.java:136)
	at org.eclipse.lemminx.extensions.contentmodel.uriresolver.XMLCacheResolverExtension.getCachedResource(XMLCacheResolverExtension.java:100)
	at org.eclipse.lemminx.extensions.contentmodel.uriresolver.XMLCacheResolverExtension.resolveEntity(XMLCacheResolverExtension.java:78)
	at org.eclipse.lemminx.uriresolver.URIResolverExtensionManager.resolveEntity(URIResolverExtensionManager.java:124)
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.resolveDocument(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.resolveSchema(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.constructTrees(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at org.eclipse.lemminx.extensions.xsd.participants.diagnostics.LSPXMLGrammarPreparser.preparseGrammar(LSPXMLGrammarPreparser.java:55)
	at org.eclipse.lemminx.extensions.xsd.participants.diagnostics.XSDValidator.doDiagnostics(XSDValidator.java:90)
	at org.eclipse.lemminx.extensions.xsd.participants.diagnostics.XSDDiagnosticsParticipant.doDiagnostics(XSDDiagnosticsParticipant.java:42)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:64)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:46)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:162)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:171)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:521)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$26(XMLTextDocumentService.java:514)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by fbricon** [comment]
Is this a regression?

**Comment by angelozerr** [comment]
No i dont think. Our xsd validator has been développed quickly compare to our xml validator. I think we should play more with it to improvise it and cover mission error ranges
