### ISSUE TITLE
DOMElement seems to not fully match the interface org.w3c.dom.Element

### ISSUE THREAD

**Issue by GitMensch** [eclipse/lemminx#1079]
`getAttributeNS()` should either return a value or `""` if the value is not set
`getElementsByTagName()` and `getElementsByTagNameNS` should always return a `NodeList`, if nothing matches an empty one (the later one is explicit that it must create a _new_ `Nodelist`).

The namespace variants specify that they may throw a  `new DOMException(NOT_SUPPORTED_ERR, msg)`.

Question: Should I PR

```diff
-		return null;
+		throw new DOMException(DOMException.NOT_SUPPORTED_ERR, "no namespace support");
```

for those (possibly only if a namespace is set) and possibly return a `new Nodelist()` for `getElementsByTagName()` or something else - or just add a comment "we don't care for the interface definition here, this is never called" (and add a RuntimeException there)?

**Comment by angelozerr** [comment]
I would prefer throwing dom exception as you suggested

**Comment by GitMensch** [comment]
OK, will do. What about the other places? Following other parts I'd throw an UnsupportedOperationCondition in the places where the class does not "match" the interface - or do you mean adding `throws DOMException` to the other functions, too?

**Comment by GitMensch** [comment]
OK, adding the exception at all places where we don't have an actual implementation in `DOMElement` showed an interesting issue (found with a bunch of failing tests): 

* the parent class `DOMNode` calls `getAttributeNode`, which it actually implements itself
* for most other parts the `DOMNode` has them also implemented, either completely or "mostly"

I now added the minor parts missing to `DOMNode` and `DOMElement` (and did some speedup for `DOMNode.getAttributeNode`), but this does change the behavior: 

* `DOMElement` behaves as it should, according to its interface
* we now have likely _more_ calls because instead of just returning `null` the method now does something

This happens, according to the initial failures quite often in the following chain:

~~~
	at org.eclipse.lemminx.dom.DOMElement.getAttributeNode(DOMElement.java:478)
	at org.eclipse.lemminx.dom.DOMDocument.createNoNamespaceSchemaLocation(DOMDocument.java:332)
	at org.eclipse.lemminx.dom.DOMDocument.initializeReferencedSchema(DOMDocument.java:282)
	at org.eclipse.lemminx.dom.DOMDocument.initializeReferencedSchemaIfNeeded(DOMDocument.java:239)
~~~

Mostly from one of the following:

~~~
	at org.eclipse.lemminx.dom.DOMDocument.getSchemaLocation(DOMDocument.java:165)
	at org.eclipse.lemminx.dom.DOMDocument.hasSchemaLocation(DOMDocument.java:177)
	at org.eclipse.lemminx.dom.DOMDocument.hasGrammar(DOMDocument.java:153)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:635)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:600)
	at org.eclipse.lemminx.services.XMLCompletions.collectTagSuggestions(XMLCompletions.java:592)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:109)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:154)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:149)
~~~
or
~~~
	at org.eclipse.lemminx.dom.DOMDocument.hasSchemaInstancePrefix(DOMDocument.java:227)
~~~

So the adjusted code seems to actually do more what it is expected to do, likely either solving and/or creating some bugs on the way...

One side note/question: lemminx has at least two different ways of handling the namespace in this area:
`DOMDocument`:

```java
	private static String getPrefixedName(String prefix, String localName) {
		return prefix != null && prefix.length() > 0 ? prefix + ":" + localName : localName; //$NON-NLS-1$
	}
```

which "widens" the valid prefix; the JavaDoc says:

> Per [XML Namespaces], applications must use the value null as the namespaceURI parameter for methods if they wish to have no namespace.

--> an empty prefix as checked here is not valid and should either be "not checked" (so the prefixed name would start with a ":") or `throw new DOMException(DOMException.NAMESPACE_ERR, "set namespace to <null> if you want no namespace");`

and the longer variant (already reordered) in `DOMNode`:

```java
		final String name;
		if (prefix != null) {
			StringBuilder sb = new StringBuilder();
			sb.append(prefix);
			sb.append(":");
			sb.append(suffix);
			name = sb.toString();
		} else {
			name = suffix;
		} 
```` 

Question 1: Is there any reason to not let the compile/VM handle that by replacing the explicit StringBuilder by string concatenation? (I left Java around 18 months ago so sorry for beginner questions).

Question 2: Shouldn't this be done identical in all places (possibly moved out to StringUtils or DOMUtils)?

Question 3: Should we check for invalid namespace content (if yes then we may also trim before...) and ignore / throw?


Last one: Should I PR the "interface matching and now done more" part (it still passes all tests) or do you have a general hint before?

**Comment by angelozerr** [comment]
Thank a lot for your advanced feedback.

When i started lemminx the fault tolerant dom document didnt implement w3c api. I found it was nice to support it to execute xpath but i did that quickly. 

In other words w3c api implementation is not perfect. If you can improvise it it should be great. As we have a lot of tests feel free to refactor anything without mailing tests.

I suggest you you create a pr, il will be easier to discuss. Thanks

**Comment by GitMensch** [comment]
I'd leave it more or less like it currently is, but would like to consolidate the internal concatenation of the namespace in #1082.

@angelozerr Can you please share your preference on this?

> Question 1: Is there any reason to not let the compile/VM handle that by replacing the explicit StringBuilder by string concatenation? (I left Java around 18 months ago so sorry for beginner questions).

> Question 2: Shouldn't this be done identical in all places (possibly moved out to StringUtils or DOMUtils)?

> Question 3: Should we check for invalid namespace content (if yes then we may also trim before...) and then ignore / throw?

**Comment by GitMensch** [comment]
Friendly ping @angelozerr and kindly asking for your preference on the namespace handling.

**Comment by angelozerr** [comment]
>Friendly ping @angelozerr and kindly asking for your preference on the namespace handling.

Thanks for pinged me, I was on vacation and I forget to give you answer.

> Question 1: Is there any reason to not let the compile/VM handle that by replacing the explicit StringBuilder by string concatenation? (I left Java around 18 months ago so sorry for beginner questions).

It's better to use StringBuilder with Java 8 (which should be supported now).

> Question 2: Shouldn't this be done identical in all places (possibly moved out to StringUtils or DOMUtils)?

StringBuilder should be used in all places, but I assume it's not the case.

> Question 3: Should we check for invalid namespace content (if yes then we may also trim before...) and then ignore / throw?

To be honnest with you, I don't know. If w3c spec says that exception must be thrown, I would say "yes", but we don't seethis exception when user is typing in the editor.
