### ISSUE TITLE
NPE while calculating referenced schema code lens

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#1099]
Make an xml file:

```xml
<dresssize>small</dresssize>
```

When you open it, you might get:

```
Message: Error while processing code lens for the participant 'org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant'.
java.lang.NullPointerException
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:124)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant.createReferencedGrammarLens(ContentModelCodeLensParticipant.java:108)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant.createReferencedGrammarLenses(ContentModelCodeLensParticipant.java:98)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant.doCodeLens(ContentModelCodeLensParticipant.java:80)
	at org.eclipse.lemminx.services.XMLCodeLens.getCodelens(XMLCodeLens.java:48)
	at org.eclipse.lemminx.services.XMLLanguageService.getCodeLens(XMLLanguageService.java:264)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$codeLens$19(XMLTextDocumentService.java:466)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by datho7561** [comment]
To reproduce this, I think you also need to configure the file to be associated with a schema using the file pattern association strategy.
