### ISSUE TITLE
NPE in CodeLens with empty XML file

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1396]
Create an empty XML file. You will see in the log

```
[Error - 16:14:05] Dec 08, 2022 04:14:05 org.eclipse.lemminx.services.XMLCodeLens getCodelens()
Message: Error while processing code lens for the participant 'org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant'.
java.lang.NullPointerException
	at org.eclipse.lemminx.utils.XMLPositionUtility.createRange(XMLPositionUtility.java:935)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant.createReferencedGrammarLenses(ContentModelCodeLensParticipant.java:94)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeLensParticipant.doCodeLens(ContentModelCodeLensParticipant.java:80)
	at org.eclipse.lemminx.services.XMLCodeLens.getCodelens(XMLCodeLens.java:51)
	at org.eclipse.lemminx.services.XMLLanguageService.getCodeLens(XMLLanguageService.java:255)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$codeLens$21(XMLTextDocumentService.java:448)
	at org.eclipse.lemminx.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:118)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by angelozerr** [comment]
@JessicaJHee or @datho7561 could you have time to investigate the problem please?

**Comment by datho7561** [comment]
I can take a look at it.
