### ISSUE TITLE
Observed IllegalArgumentException from ContentModelCompletionParticipant

### ISSUE THREAD

**Issue by jesse-gallagher** [eclipse/lemminx#602]
It comes from this line: https://github.com/angelozerr/lsp4xml/blob/e8dd978b44a6867466dd0ad356d0f88655201c9f/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/participants/ContentModelCompletionParticipant.java#L204 
Presumably, `tagName` ends up null or empty, so maybe it'd make sense to filter those out.

This is logged from the `XMLCompletions#collectOpenTagSuggestions` method, so it doesn't throw all the way to the top, but it likely cuts off contribution of further content model elements.

```
Jan 03, 2020 2:31:18 PM org.eclipse.lsp4xml.services.XMLCompletions collectOpenTagSuggestions
SEVERE: While performing ICompletionParticipant#onTagOpen
java.lang.IllegalArgumentException: Property must not be null: label
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
	at org.eclipse.lsp4j.CompletionItem.<init>(CompletionItem.java:136)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:204)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithChildrenElementDeclaration(ContentModelCompletionParticipant.java:167)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithPossibleElementDeclaration(ContentModelCompletionParticipant.java:134)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.onTagOpen(ContentModelCompletionParticipant.java:74)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:493)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:467)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectTagSuggestions(XMLCompletions.java:459)
	at org.eclipse.lsp4xml.services.XMLCompletions.doComplete(XMLCompletions.java:98)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doComplete(XMLLanguageService.java:136)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:175)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1307)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1276)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

I'm able to reproduce it regularly using this document, once I add in a non-namespaced tag like `<foo>` here and then start opening another tag:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xp:view xmlns:xp="http://www.ibm.com/xsp/core" xmlns:xc="http://www.ibm.com/xsp/custom">
	<foo>

	</foo>
</xp:view>
```

The same doesn't happen if I make a version of that document with all the prefixes and namespaces removed.

**Comment by angelozerr** [comment]
Thanks for your great explanation. Is there any chance to have a pr with a test ?

**Comment by jesse-gallagher** [comment]
I don't have a workspace set up currently, but I'll aim to get a working environment set up when I have a chance.

**Comment by angelozerr** [comment]
Same issue than https://github.com/eclipse/lemminx/issues/613
