### ISSUE TITLE
NPE when document contains an empty tag

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#613]
Trying to complete
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<goals><goal>list</goal></goals>
						<configuration>
							<>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```
in the empty tag inside `configuration`, I get
```
SEVERE: While performing ICompletionParticipant#onTagOpen
java.lang.IllegalArgumentException: Property must not be null: label
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
	at org.eclipse.lsp4j.CompletionItem.<init>(CompletionItem.java:136)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:204)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.addTagName(ContentModelCompletionParticipant.java:212)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithChildrenElementDeclaration(ContentModelCompletionParticipant.java:167)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithPossibleElementDeclaration(ContentModelCompletionParticipant.java:134)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.ContentModelCompletionParticipant.onTagOpen(ContentModelCompletionParticipant.java:74)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:493)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:467)
	at org.eclipse.lsp4xml.services.XMLCompletions.collectTagSuggestions(XMLCompletions.java:459)
	at org.eclipse.lsp4xml.services.XMLCompletions.doComplete(XMLCompletions.java:98)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doComplete(XMLLanguageService.java:136)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:175)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

As mentioned in #612, the schema proposals here don't make sense. So it's very likely that this issue disappear when #612 is fixed.
However, it may surface in other cases, so a null-check should probably be added.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/620
