### ISSUE TITLE
NPE Highlighting with <!ELEMENT

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#677]
```xml
<!DOCTYPE root-element [	
	<!ELEMENT
]>
<root-element>
</root-element>
```

Set cursor inside <!ELEMENT, you will se the NPE:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.lemminx.dom.DTDElementDecl.getParameterAt(DTDElementDecl.java:98)
	at org.eclipse.lemminx.extensions.dtd.participants.DTDHighlightingParticipant.findDocumentHighlights(DTDHighlightingParticipant.java:54)
	at org.eclipse.lemminx.services.XMLHighlighting.fillWithCustomHighlights(XMLHighlighting.java:125)
	at org.eclipse.lemminx.services.XMLHighlighting.findDocumentHighlights(XMLHighlighting.java:67)
	at org.eclipse.lemminx.services.XMLLanguageService.findDocumentHighlights(XMLLanguageService.java:114)
```

**Comment by angelozerr** [comment]
This bug was fixed with https://github.com/eclipse/lemminx/commit/a3826946343819a9528a8118e20434cb859d2fd0#diff-f446d1194bec624db9c2b077b98961c3R107
