### ISSUE TITLE
NPE with Codelens in empty XSD file

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#684]
Create an empty XSD file, activate Codelens and type a space:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.lemminx.extensions.xsd.utils.XSDUtils.getTargetAttrs(XSDUtils.java:305)
	at org.eclipse.lemminx.extensions.xsd.utils.XSDUtils.searchXSOriginAttributes(XSDUtils.java:258)
	at org.eclipse.lemminx.extensions.xsd.participants.XSDCodeLensParticipant.doCodeLens(XSDCodeLensParticipant.java:50)
	at org.eclipse.lemminx.services.XMLCodeLens.getCodelens(XMLCodeLens.java:42)
	at org.eclipse.lemminx.services.XMLLanguageService.getCodeLens(XMLLanguageService.java:244)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$codeLens$17(XMLTextDocumentService.java:377)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
```

**Comment by datho7561** [comment]
I'd be interested in this issue
