### ISSUE TITLE
Error while saving file to cache on Windows OS (PosixFileAttributeView not supported)

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#734]
Remove the .lemminx folder cache, create a XSD file and open completion

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ui">
|
<xs:schema>
```

The file is correctly created in the .lemminx folder, but in the log I have this error. This bug occurs on Windows OS .

```
Error - 11:31:50] May 28, 2020 11:31:50 org.eclipse.lemminx.utils.FilesUtils saveToFile()
Message: The associated file system 'C:\Users\azerr\.lemminx\cache\http\www.w3.org\2001\XMLSchema.xsd' + does not support the PosixFileAttributeView
java.lang.UnsupportedOperationException
	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2078)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:155)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:135)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:207)
	at org.eclipse.lemminx.extensions.xsd.XSDURIResolverExtension.resolve(XSDURIResolverExtension.java:61)
	at org.eclipse.lemminx.uriresolver.URIResolverExtensionManager.resolve(URIResolverExtensionManager.java:93)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.findCMDocument(ContentModelManager.java:180)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.findCMDocument(ContentModelManager.java:131)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.findCMDocument(ContentModelManager.java:94)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.findCMDocument(ContentModelManager.java:90)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.onTagOpen(ContentModelCompletionParticipant.java:71)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:608)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:733)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:224)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:139)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:189)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by datho7561** [comment]
I could take a look at this.
