### ISSUE TITLE
StringIndexOutOfBoundsException in EntityNotDeclaredCodeAction.getEntityName

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#862]
The following content causes lemminx to throw an exception:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE suite SYSTEM 'https://testng.org/testng-1.0.dtd'>
<sweet
  name='Testos'
  verbose='5'>
  <test name='s'>
    &bar;
    <packages>
      <package name='uitest.*' />
    </packages>
  </test>
</sweet>
``` 

```
[Error - 8:01:16 PM] Sep. 01, 2020 08:01:16 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 0
java.util.concurrent.CompletionException: java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 0
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1309)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1276)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.EntityNotDeclaredCodeAction.getEntityName(EntityNotDeclaredCodeAction.java:229)
	at org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.EntityNotDeclaredCodeAction.doCodeAction(EntityNotDeclaredCodeAction.java:49)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCodeActionParticipant.doCodeAction(ContentModelCodeActionParticipant.java:49)
	at org.eclipse.lemminx.services.XMLCodeActions.doCodeActions(XMLCodeActions.java:45)
	at org.eclipse.lemminx.services.XMLLanguageService.doCodeActions(XMLLanguageService.java:255)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$codeAction$19(XMLTextDocumentService.java:389)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1307)
	... 7 more
```

**Comment by angelozerr** [comment]
@fbricon I cannot reproduce it?

**Comment by angelozerr** [comment]
I tested with vscode-xml 1.3.0 and it works too.
